BEGIN;

DROP TABLE maritials CASCADE;
DROP TABLE educations CASCADE;
DROP TABLE genders CASCADE;
DROP TABLE card_categories CASCADE;
DROP TABLE income_categories CASCADE;
DROP TABLE attrition_flags CASCADE;
DROP TABLE clients CASCADE;

COMMIT;
