// Code generated by SQLBoiler 4.7.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	AttritionFlags   string
	CardCategories   string
	Clients          string
	Educations       string
	Genders          string
	IncomeCategories string
	Maritials        string
}{
	AttritionFlags:   "attrition_flags",
	CardCategories:   "card_categories",
	Clients:          "clients",
	Educations:       "educations",
	Genders:          "genders",
	IncomeCategories: "income_categories",
	Maritials:        "maritials",
}
